### ISSUE TITLE
Needed libraries for compiling immutable-xjc, esp. unit test code?

### ISSUE THREAD

**Issue by dirkhillbrecht** [sabomichal/immutable-xjc#20]
I cannot find any information about the needed libraries for compiling immutable-xjc. I am using Java 8 and have added jaxb-core/-impl/-xjc, stax-api and activation into the class path. I still get errors in the unit test code where classes like "Model", "Parameters" or "NameExpression" are not found. What do I have to add?

**Comment by sabomichal** [comment]
May you post the exact command you are executing when trying to compile?

**Comment by dirkhillbrecht** [comment]
Hi, I've just imported the project into Eclipse and added the mentioned libraries as external JAR references. Eclipse marks no errors in the PluginImpl code but a number of "class not found" errors for these classes:

Model, Parameters, Declaration, NameExpression

I understand that they seem to be not even imported.

The classpath contains:

- activation-1.1
- jaxb-core-2.2.11
- jaxb-impl-2.2.11
- jaxb-xjc-2.2.11
- stax-api-1.0.1
- JRE System Library from jdk-1.8.0_111
- JUnit 4

**Comment by sabomichal** [comment]
please import it as maven project or build it with maven straightaway - `mvn package` or `mvn install`

**Comment by dirkhillbrecht** [comment]
Ok, I get an idea of what's happening: These classes "Model", "Parameters" etc. should be created for the test cases from the WSDLs in the package. But for some reasons they aren't. My knowledge of Maven is rather limited (it's "sbt" land over here...) but I tried "mvn generate-sources" which did nothing. Then, I tried "mvn generate-sources:wsdl2java" which threw an error (line breaks added):

    [ERROR] No goals have been specified for this build.
    You must specify a valid lifecycle phase or a goal in the format
    <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>.
    Available lifecycle phases are: validate, [...]

I'm still stuck...

**Comment by sabomichal** [comment]
if you look at the build configuration defined in pom.xml, you will notice that the plugins bound to `generate-sources` and `generate-test-sources` phase are part of the `selftest` profile. In order to generate these classes (you are right, they are only needed for testing), you have to activate this profile.
Run `mvn clean install` and afterwards `mvn install -P selftest`. The test classes will be generated as part of the build process.
If you need to generate just these classes then run  `mvn generate-sources -P selftest` and  `mvn generate-test-sources -P selftest`.

Nevertheless I see there a minor bug, the plugins bound to generate-sources phase should be bound to generate-test-sources phase instead. I am going to fix that.
